apiVersion: batch/v1
kind: Job
metadata:
  name: "myapp"
spec:
  template:
    metadata:
      name: "myapp"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: postgres:latest
        env:
          - name: POSTGRES_PASSWORD
            value: "passwd"
        command:
          - sh
          - "-c"
          - |
            psql postgres://myuser:passwd@myapp-postgresql/myapp <<'EOF'
              create table users (id bigint primary key, username varchar, firstName varchar, lastName varchar, email varchar, phone varchar);              
            EOF
 
  backoffLimit: 0